# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-30 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecentMediaScraper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anime',
        ),
        migrations.DeleteModel(
            name='TVShow',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='lead_actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(default=False, verbose_name='adult'),
        ),
        migrations.AddField(
            model_name='movie',
            name='backdrop_path',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_ids',
            field=models.CommaSeparatedIntegerField(default=[], max_length=30),
        ),
        migrations.AddField(
            model_name='movie',
            name='media_id',
            field=models.PositiveIntegerField(default=1, verbose_name='id'),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_language',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.TextField(default='', verbose_name='overview'),
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.PositiveIntegerField(default='0', verbose_name='vote_count'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(default='', verbose_name='date released'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
