# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-08 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecentMediaScraper', '0002_auto_20160330_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='popularity',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=12),
        ),
    ]
