# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-18 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecentMediaScraper', '0005_auto_20160408_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_enforce', models.PositiveIntegerField(default=1, unique=True)),
                ('TMDB_baseurl', models.CharField(default=' ', max_length=300)),
                ('TMDB_size', models.CharField(default=' ', max_length=50)),
            ],
        ),
    ]
